server:
  port: 8087

spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureke-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client

