server:
  port: 8080
  servlet:
    context-path: /consumer

logging:
  pattern:
    console: level-%level %msg%n
    level:
      root: info
      com.arthur: debug

spring:
  application:
    name: consumer-depart

eureka:
  instance:
    instance-id: consumer-8080
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka



