server:
  port: 8081

logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    com.arthur: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///local_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: arthur
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.arthur.model