server:
  port: 8082
  servlet:
    context-path: /provider

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
  instance:
    instance-id: provider-8082

spring:
  application:
    name: provider-depart
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///local_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    #username: arthur
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.arthur.model

info:
  auth: Arthur
  app.name: spring-cloud-provider
  app.desc: This is my first test for Spring Cloud
  company.name: wondersgroup
  company.addr: Shanghai China





