server:
  port: 8086

spring:
  application:
    name: service-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-hystrix-dashboard
  cluster-name-expression: new String("default")






